### ISSUE TITLE
fix recordings with wrong alignment

### ISSUE THREAD

**Issue by leandermasopust** [Sensors-in-Paradise/ml-rainbow#26]
## Description

Write a script to convert all recordings with a wrong alignment.
Those recordings are stored under "Wrong Sensor Orientation Data" and described within the subfolder naming.
There are multiple Recordings per subfolder/per alignment issue.

## Must Include

- [ ] find a conversion calculation for quat
- [x] find a conversion calculation for dq
- [x] find a conversion calculation for dv
- [ ] find a conversion calculation for mag

- [x] write a script for each wrong sensor alignment
- [x] save modified dataframes into new csv files 
- [ ] check correctness of modified dataframes by visualizing the data partially (3d plot)

**Comment by treyfel** [comment]
Our solution works out fine for dq, dv. still some problems with mag. In our sample recordings, the slope of mag can be aligned using a simple 3x3 rotation matrix but the data is still not at the same values. we tried a translation vector to fix this but that doesnt work for both recordings as the reference values dont match. to further investigate this other reference recordings have to be made.

**Comment by alexanderwischmann** [comment]
Every script related to this issue lies in  ML-Rainbow/data_conversion.
calculateRotation.py does the actual data conversion . It supports testing and comparing of one-sensor-Recording conversion(s) and actual creation of new, converted files.
gridSearchQuatRotation.py is used to do grid Searches on customisable Parameters of the conversion for a specific feature (for example the transformation Matrix used to rotate Quaternions).

plot_2D_graph can be used to visualize converted Recordings.

**Comment by lucasliebe** [comment]
will not be worked on further
